<#
.SYNOPSIS
    Script used for repo mirroring to auto update internal mirror branches and
    create PRs for submodule updates.

.DESCRIPTION
    Script used in the build pipeline to mirror submodules like MU_BASECORE that
    will automatically update the internal mirror

    The following powershell code will need to be copied to the build pipeline,
    which will then call this script:

    Write-Host "git push https://User:$(PAT.OS)@$(Internal.Url) HEAD:$(Build.SourceBranch) --tags"
    git push https://User:$(PAT.OS)@$(Internal.Url) HEAD:$(Build.SourceBranch) --tags

    $remoteHead = git rev-parse HEAD

    cd ..

    git clone https://User:$(PAT.OS)@$(Parent.Url) hyperv.uefi
    cd hyperv.uefi
    git checkout origin/$(Parent.CurrentBranch)
    .\MsvmPkg\MirrorPipeline.ps1 -RemoteHead $remoteHead -PATOS $(PAT.OS)

    The following build pipline variables need to be defined:
    Internal.Url            - The clone URL of the internal mirror, ie dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_basecore
    Parent.CurrentBranch    - The branch of this repo (hyperv.uefi) to check against, ie official/19H2_Vibranium
    Parent.SubmoduleName    - The name of the submodule being checked
    Parent.SubmodulePath    - The path to the submodule from the root of the repo
    Parent.Url              - The clone URL of this repo, ie dev.azure.com/microsoft/OS/_git/hyperv.uefi
    PAT.OS                  - A secret variable that contains a PAT with code read/write access to the OS project.

.PARAMETER RemoteHead
    The commit hash of the HEAD of the remote submodule.

.PARAMETER PATOS
    The PAT.OS to use for authentication.
#>

param(
    [string]$RemoteHead,
    [string]$PATOS
    )

# Patch PAT into .gitmodules
git config --file=.gitmodules submodule.$env:Parent_SubmoduleName.url "https://User:$PATOS@$env:Internal_Url"
git submodule sync

git submodule update --init $env:Parent_SubmodulePath
cd $env:Parent_SubmodulePath

$submoduleHead = git rev-parse HEAD

if ($remoteHead -ne $submoduleHead)
{
    Write-Host "submodule out of date, creating branch"

    # Create new branch with updated submodule
    git config user.email "uefibot@microsoft.com"
    git config user.name "uefibot"
    git pull https://User:$PATOS@$env:Internal_Url HEAD:$env:Build_SourceBranch

    $branchname = "user/uefibot/$env:Parent_SubmoduleName-update-" + (get-date -Format FileDateTimeUniversal)
    write-host $branchname

    cd ..
    $branchname = "user/uefibot/$env:Parent_SubmoduleName-update-" + (get-date -Format FileDateTimeUniversal)
    write-host "branch name is: " + $branchname
    git checkout -b $branchname
    git add $env:Parent_SubmodulePath

    # Update cgmanifest.json
    $cg = Get-Content -Raw -Path .\cgmanifest.json | ConvertFrom-Json
    $cg.Registrations.Where({ $_.component.git.repositoryUrl -eq "https://$env:Internal_Url"}).component.git.commitHash = $remoteHead
    $cg | ConvertTo-Json -depth 10 | Out-File .\cgmanifest.json
    git add cgmanifest.json

    git status

    git config user.email "uefibot@microsoft.com"
    git config user.name "uefibot"
    git commit -m "Submodule update from upstream"

    # push branch
    git push --set-upstream origin $branchname

    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "user","$PATOS")))
    $head = @{ Authorization = "Basic $base64AuthInfo" }

    # Get user ID for reviewers
    # requires the VSTS ID, which can be gotten using their REST API. However,
    # hardcoded here since the microsoft organization has so many people it's not
    # simple to query them.
    # OS\ft_mvm, mebersol, cho
    $userIds = @( @{ "id" = "aeb49097-8f31-4bdd-a34f-79df58f1c27d" },
        @{ "id" = "df46db82-f286-4371-9eed-454521469291" },
        @{ "id" = "2ebf9154-a7be-4033-9af5-b80115b5b5c1" })

    # create PR
    $requestBody = @{
        sourceRefName = "refs/heads/$branchname"
        targetRefName = "refs/heads/$env:Parent_CurrentBranch"
        title = "[UEFIBOT] $env:Parent_SubmoduleName upstream submodule update"
        description = "AUTOGENERATED `n PENDING: TESTS."
        reviewers = @($userIds)
    }

    Write-Host "The source branch is: $($requestBody.sourceRefName)"
    Write-Host "The target branch is: $($requestBody.targetRefName)"
    Write-Host "The title is: $($requestBody.title)"

    $url = "$env:System_TeamFoundationCollectionUri$env:System_TeamProject/_apis/git/repositories/hyperv.uefi/pullrequests?api-version=5.0"

    $jsonBody = ConvertTo-Json $requestBody
    $response =  Invoke-RestMethod -Uri $url -Method Post -Headers $head -Body $jsonBody -ContentType application/json
    if($response -ne $Null)
    {
        Write-Host "Pull Request $($response.pullRequestId) successfully created."
    }
}

