/*++

Copyright (c) Microsoft Corporation

Module Name:

    Console.h

Abstract:

    The Hyper-V Null Console Driver.

Author:

    Larry Cleeton (lcleeton) - 01-Dec-2014

--*/


#pragma once

#include <EfiNt.h>
#include <Protocol/DevicePath.h>
#include <Library/DebugLib.h>
#include <Library/UefiDriverEntryPoint.h>
#include <Library/UefiLib.h>
#include <Library/DevicePathLib.h>
#include <Library/BaseMemoryLib.h>
#include <Library/MemoryAllocationLib.h>
#include <Library/UefiBootServicesTableLib.h>

//
// Driver Binding Externs
//
extern EFI_DRIVER_BINDING_PROTOCOL  gConsoleDriver;
extern EFI_COMPONENT_NAME_PROTOCOL  gConsoleComponentName;
extern EFI_COMPONENT_NAME2_PROTOCOL gConsoleComponentName2;

//
// Autogenerated GUID.
//
extern EFI_GUID gMsvmConsoleProtocolGuid;

//
// Prototypes
// Driver model protocol interface
//
EFI_STATUS
EFIAPI
ConsoleDriverSupported(
    _In_ EFI_DRIVER_BINDING_PROTOCOL    *This,
    _In_ EFI_HANDLE                     Controller,
    _In_ EFI_DEVICE_PATH_PROTOCOL       *RemainingDevicePath
    );

EFI_STATUS
EFIAPI
ConsoleDriverStart(
    _In_ EFI_DRIVER_BINDING_PROTOCOL    *This,
    _In_ EFI_HANDLE                     Controller,
    _In_ EFI_DEVICE_PATH_PROTOCOL       *RemainingDevicePath
    );

EFI_STATUS
EFIAPI
ConsoleDriverStop(
    _In_  EFI_DRIVER_BINDING_PROTOCOL   *This,
    _In_  EFI_HANDLE                    Controller,
    _In_  UINTN                         NumberOfChildren,
    _In_  EFI_HANDLE                    *ChildHandleBuffer
    );

//
// EFI Component Name Functions
//
EFI_STATUS
EFIAPI
ConsoleComponentNameGetDriverName(
    _In_  EFI_COMPONENT_NAME_PROTOCOL   *This,
    _In_  CHAR8                         *Language,
    _Out_ CHAR16                        **DriverName
    );


EFI_STATUS
EFIAPI
ConsoleComponentNameGetControllerName(
    _In_  EFI_COMPONENT_NAME_PROTOCOL   *This,
    _In_  EFI_HANDLE                    ControllerHandle,
    _In_opt_ EFI_HANDLE                 ChildHandle,
    _In_  CHAR8                         *Language,
    _Out_ CHAR16                        **ControllerName
    );

//
// Simple Text Input interface
//
EFI_STATUS
EFIAPI
ConsoleInReset(
    _In_ EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This,
    _In_ BOOLEAN                        ExtendedVerification
    );

EFI_STATUS
EFIAPI
ConsoleInReadKeyStroke(
    _In_ EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This,
    _Out_ EFI_INPUT_KEY                 *Key
    );

//
// Simple Text Output interface
//
EFI_STATUS
EFIAPI
ConsoleOutReset(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ BOOLEAN                         ExtendedVerification
    );

EFI_STATUS
EFIAPI
ConsoleOutOutputString(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ CHAR16                          *String
    );

EFI_STATUS
EFIAPI
ConsoleOutTestString(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ CHAR16                          *String
    );

EFI_STATUS
EFIAPI
ConsoleOutQueryMode(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ UINTN ModeNumber,
    _Out_ UINTN *Columns,
    _Out_ UINTN *Rows
    );

EFI_STATUS
EFIAPI
ConsoleOutSetMode(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ UINTN                           ModeNumber
    );

EFI_STATUS
EFIAPI
ConsoleOutSetAttribute(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ UINTN                           Attribute
    );

EFI_STATUS
EFIAPI
ConsoleOutClearScreen(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This
    );

EFI_STATUS
EFIAPI
ConsoleOutSetCursorPosition(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ UINTN                           Column,
    _In_ UINTN                           Row
    );

EFI_STATUS
EFIAPI
ConsoleOutEnableCursor(
    _In_ EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    _In_ BOOLEAN                         Visible
    );
