parameters:
- name: pipeline
  type: string
  values:
  - Official
  - PR

# This controls only Nuget create, not Vpack creation.
# Due to upstream code/policy, vpacks cannot be created in the PR pipeline.
# The official "CI" pipeline, which creates vpacks, can be run against PRs with approval.
- name: publishNuget
  type: boolean
  default: False
###############################################################################
# constants
- name: Nugets
  type: object
  default: [
    {definition: llvm.tools,    version: $(LlvmVersion), feed: $(LlvmFeed), downloadPath: $(PkgLlvm_Tools)},
    {definition: clang.headers, version: $(LlvmVersion), feed: $(LlvmFeed), downloadPath: $(PkgClang_Headers)}]
- name: Builds
  type: object
  # gcc is not to ship, because no Codeview and 64K aligned files (64K is easily fixed by using mingw tools).
  # gcc could be Windows-hosted if backward slashes are fixed.
  # Clang/amd64 is not yet to ship, stubs out assembly.
  default: [
    # TODO: What order for the columns?
    # TODO: What redundancy vs. derivation?
    {Pool: Windows, Windows: True, Arch:     X64, Target:   DEBUG, ToolChainTag: VS2022, Extra: BLD_*_LEGACY_DEBUGGER=1},
    {Pool: Windows, Windows: True, Arch:     X64, Target: RELEASE, ToolChainTag: VS2022},

    #
    # Salt (adds to flavor, for non-production builds):
    #
    # Not perfectly systematic.
    # CV implies W.
    # CW implies W.
    #
    # Arch (not needed)   Target (not needed)    Tool            BuildHostOS (Pool)
    # A arm64             D debug                G  gcc          L Linux
    # X X64               R release              CV ClangVS      W Windows
    #                                            CW ClangWindows
    #                                            CL ClangLinux
    #                                            V  VS? M MSVC?
    #                                            M  Mingw?
    #                                            CP CLANGPDB?
    #                                            CD CLANGDWARF?
    #                                            CE CLANGELF?
    #                                            CP CLANGPE?
    #                                            GE GCCELF?
    #                                            GP GCCPE?
    #
    # Probably this should be the order for these columns.
    #
    # CLANG_BIN: Trailing slash is required. Setting this unconditionally (in vars.xml) breaks Linux build.
    {Pool: Windows, Windows: True, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}, Extra: BLD_*_LEGACY_DEBUGGER=1},
    {Pool: Windows, Windows: True, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},
    {Pool: Windows, Windows: True, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: ADCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},
    {Pool: Windows, Windows: True, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: ARCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},

    {Pool: Windows, Windows: True, ClangWindows: True, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}, Extra: BLD_*_LEGACY_DEBUGGER=1},
    {Pool: Windows, Windows: True, ClangWindows: True, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},
    {Pool: Windows, Windows: True, ClangWindows: True, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},
    {Pool: Windows, Windows: True, ClangWindows: True, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},

    {Pool: Linux, Linux: True, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCL, Extra: BLD_*_LEGACY_DEBUGGER=1},
    {Pool: Linux, Linux: True, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCL},
    {Pool: Linux, Linux: True, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: ADCL},
    {Pool: Linux, Linux: True, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: ARCL},

    # Temporarily disable Gcc debug build.
    # Probably depends on https://github.com/microsoft/mu_basecore/pull/1710 DisableNullDetection: Make calling convention consistent.
    #{Pool: Linux, Linux: True, Arch:     X64, GnuArch: "x86-64", Target:   DEBUG, ToolChainTag: GCC, Salt: XDG, Extra: BLD_*_LEGACY_DEBUGGER=1},
    {Pool: Linux, Linux: True, Arch:     X64, GnuArch: "x86-64", Target: RELEASE, ToolChainTag: GCC, Salt: XRG},
    {Pool: Linux, Linux: True, Arch: AARCH64, GnuArch: aarch64, Target:   DEBUG, ToolChainTag:  GCC, Salt: ADG},
    {Pool: Linux, Linux: True, Arch: AARCH64, GnuArch: aarch64, Target: RELEASE, ToolChainTag:  GCC, Salt: ARG}
    ]
###############################################################################
jobs:
  - ${{ each Build in parameters.Builds }}:
    # Keep historical job names for VS2022 and append _Salt for GCC/CLANGPDB.
    - job: ${{Build.Target}}_${{Build.Arch}}_${{Build.ToolChainTag}}${{iif(ne(Build.Salt, ''), format('_{0}', Build.Salt), '')}}
      pool:
        type: ${{ Build.Pool }}
      variables:
        ${{if Build.Linux}}:
          script_start: "cat $0"
        ${{else}}:
          script_start: "@echo on\n@type %0"
        powershell_start: "Get-Content $PSCommandPath"

        ${{each pair in Build.Env}}:
          ${{pair.Key}}: ${{pair.Value}}

        # Salted names are appended ".Test", no matter PR or Official.
        # PR names are also appended ".Test".
        # Append ".Test" at most once.
        DotSalt: ${{iif(eq(Build.Salt, ''), '', format('.{0}', Build.Salt))}}
        DotTest: ${{iif(or(ne(Build.Salt, ''), eq(parameters.pipeline, 'PR')), '.Test', '')}}

        # Hypothetical Python version to install, not used.
        Env.PythonVersion: "3.10"

        # GCC prefix for Linux-hosted builds.
        GCC_${{Build.Arch}}_PREFIX: '/usr/bin/${{Build.GnuArch}}-linux-gnu-'

        GIT_TERMINAL_PROMPT: "0"

        # Docker images to host pipeline on.
        # https://eng.ms/docs/products/onebranch/infrastructureandimages/containerimages/containerimages
        # TODO: Switch to AzureLinux
        LinuxContainerImage:   'onebranch.azurecr.io/linux/ubuntu-2404:latest'

        BuildDir: Build/Msvm${{Build.Arch}}/${{Build.Target}}_${{Build.ToolChainTag}}
        PlatformPkg: MsvmPkg
        WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # https://aka.ms/obpipelines/containers

        # OneBranch, VPack, Nuget configuration.

        # Job name is included in artifact path and non-matrix job names must be unique.
        # Otherwise we would have "UnderSalt" like "DotSalt".
        # ob_artifactSuffix: '_${{Build.Arch}}_${{Build.Target}}'
        ob_outputDirectory:            $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT
        ob_nugetPublishing_enabled:    ${{parameters.publishNuget}}

        # $(PRdot) is always empty in Official "CI" builds, and always non-empty in PR builds.
        # $(DotSalt) is empty in "more official" builds intended to be productized
        # and non-empty to disambiguate experimental variants.
        # $(DotTest) is also non-empty in PR builds (there is redundancy).
        ob_createvpack_packagename:    $(Build.Repository.Name).mscoreuefi.$(PRdot)${{Build.Arch}}.${{Build.Target}}$(DotSalt)$(DotTest)
        ob_createvpack_description:    Hyper V UEFI Firmware

        # Vpack is always enabled on Official "CI" builds here.
        # Due to upstream code/policy, vpacks cannot be created in the PR pipeline. Setting this to True is ignored there.
        ob_createvpack_enabled:        True

        ob_createvpack_versionAs:      parts
        ob_createvpack_majorVer:       $(Parameters.vPack.majorVer)
        ob_createvpack_minorVer:       $(Parameters.vPack.minorVer)
        # SourceVersion is git hash, e.g. ba4edab919b22064ffd06911f5f3413b78889c9e.
        ob_createvpack_metadata:       $(Build.SourceVersion)
        ob_createvpack_failOnStdErr:   True
        ob_createvpack_verbose:        True
        ob_createvpack_vpackdirectory: $(ob_outputDirectory)/$(BuildDir)/Bin
###############################################################################
      steps:
      - script: set
        displayName: set

      - task: NuGetAuthenticate@1
        inputs:
          nuGetServiceConnections: WindowsPartners_NugetFeedConnection

      - task: PipAuthenticate@1
        displayName: pip_auth
        inputs:
          artifactFeeds: $(System.TeamProject)/$(System.TeamProject)_PublicPackages

      - script: |
          $(script_start)
          git config --global http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_basecore.extraheader "AUTHORIZATION: Bearer $(System.AccessToken)"
          git config --global http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_tiano_plus.extraheader "AUTHORIZATION: Bearer $(System.AccessToken)"
        displayName: Set access token

      - script: python --version
        displayName: python_version

      # Python install fails on Linux and is not needed in any case.
      #- task: UsePythonVersion@0
      #  displayName: Install Python $(Env.PythonVersion)
      #  inputs:
      #    versionSpec: $(Env.PythonVersion)
      #    architecture: x64

      - ${{if Build.Linux}}:
        - script: apt-get update -y
          displayName: apt_up

        # gcc-* fails because of multiple version numbers.
        - ${{if eq(Build.ToolChainTag, 'CLANGPDB')}}:
          - script: apt-get install -y clang lld llvm
            displayName: apt_inst_clang
        - ${{else}}:
          - script: apt-get install -y binutils-${{Build.GnuArch}}-linux-gnu gcc-${{Build.GnuArch}}-linux-gnu
            displayName: apt_inst_gcc_${{Build.GnuArch}}

      # The nugets are downloaded into a strict read only cachable form, one Nuget per directory, like CoreXT.
      # Then copied to how clang wants them.
      - ${{if Build.ClangWindows}}:
        - ${{each Nuget in parameters.Nugets}}:
          - task: DownloadPackage@1
            displayName: get ${{Nuget.definition}}
            inputs: ${{Nuget}}
        # Always clean install.
        - script: |
            $(script_start)
            :: quotes to accomodate forward slashes
            rmdir /q/s                          "$(CLANGWIN)"
            xcopy /fivery "$(PkgLlvm_Tools)"    "$(CLANGWIN_BIN)" || goto :eof
            xcopy /fivery "$(PkgClang_Headers)" "$(CLANGWIN_INC)" || goto :eof
          displayName: install Windows clang

      - script: python -m pip install --upgrade -r pip_requirement_stable.txt --force-reinstall --no-cache-dir
        displayName: pip

      - script: python $(PlatformPkg)/PlatformBuild.py --setup
        displayName: Setup

      - script: python $(PlatformPkg)/PlatformBuild.py --update
        displayName: Update

      # This is the main task, compile and link.
      - script: python $(PlatformPkg)/PlatformBuild.py ${{Build.Extra}} tool_chain_tag=${{Build.ToolChainTag}} BUILDREPORTING=TRUE BUILDREPORT_TYPES="PCD DEPEX FLASH BUILD_FLAGS LIBRARY" TARGET=${{Build.Target}} BUILD_ARCH=${{Build.Arch}} LaunchLogOnSuccess=FALSE LaunchLogOnError=FALSE
        displayName: Build

      # When previous fails, this is the main/usual way to debug.
      - ${{if Build.Linux}}:
        - script: ls Build; cat Build/B*.txt
          condition: succeededOrFailed()
          continueOnError: True
          displayName: logs
      - ${{else}}:
        - script: dir Build & type Build\B*.txt
          condition: succeededOrFailed()
          continueOnError: True
          displayName: logs

      - task: CopyFiles@2
        condition: succeededOrFailed()
        continueOnError: True
        displayName: artifact_logs
        inputs:
          TargetFolder: $(ob_outputDirectory)/Build Logs $(Agent.JobName)
          SourceFolder: Build
          contents: |
            BuildLog.txt
            BUILDLOG_*.txt
            BUILDLOG_*.md
            **/BUILD_REPORT.txt
            CI_*.txt
            CI_*.md
            CISETUP.txt
            SETUPLOG.txt
            UPDATE_LOG.txt
            PREVALLOG.txt
            TestSuites.xml
            **/BUILD_TOOLS_REPORT.html
            **/OVERRIDELOG.TXT
            BASETOOLS_BUILD*.*
            **/FD_REPORT.HTML
          flattenFolders: True

      # When build fails, if logging is not enough to debug, try downloading this artifact.
      - task: CopyFiles@2
        condition: failed()
        continueOnError: True
        displayName: Copy all, for debugging
        inputs:
          SourceFolder: Build
          Contents: '**'
          TargetFolder: $(ob_outputDirectory)/all

      - task: CopyFiles@2
        displayName: artifact_fd
        inputs:
          Contents: $(BuildDir)/FV/MSVM.fd
          TargetFolder: $(ob_outputDirectory)/Firmware Binary File ${{Build.Target}}_${{Build.Arch}}

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: CopyFiles@2
          displayName: artifact_pdbs
          inputs:
            SourceFolder: $(BuildDir)/PDB/
            Contents: '**'
            TargetFolder: $(ob_outputDirectory)/Firmware PDB Files ${{Build.Target}}_${{Build.Arch}}

      - task: CopyFiles@2
        displayName: artifact_maps
        inputs:
          SourceFolder: $(BuildDir)/MAP/
          Contents: '**'
          TargetFolder: $(ob_outputDirectory)/Firmware Map Files ${{Build.Target}}_${{Build.Arch}}

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: PublishSymbols@2
          displayName: PublishSymbols
          inputs:
            SearchPattern: $(BuildDir)/PDB/*.pdb
            IndexSources: True
            SymbolServerType: TeamServices
            SymbolsProduct: Hyper-V UEFI
            enablesymbolspublishing: True
          continueOnError: True

      - task: Powershell@2
        displayName: vpack_firmware
        inputs:
          targetType: inline
          script: |
            $(powershell_start)
            $folder = "$(ob_createvpack_vpackdirectory)"
            New-Item $folder -Type Directory
            copy-item "$(BuildDir)/FV/MSVM.fd" $folder
            copy-item "$(BuildDir)/${{Build.Arch}}/MsvmPkg/AcpiTables/AcpiTables/OUTPUT/Dsdt.aml" $folder
            copy-item "MsvmPkg/Include/BiosInterface.h" $folder

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: Powershell@2
          displayName: vpack_pdb
          inputs:
            targetType: inline
            script: |
              $(powershell_start)
              $folder = "$(ob_createvpack_vpackdirectory)"
              copy-item "$(BuildDir)/PDB" $folder -Recurse

      - task: NuGetCommand@2
        displayName: pack_nuget
        inputs:
          command: pack
          packagesToPack: $(PlatformPkg)/HyperVUefi.NuSpec
          packDestination: $(ob_outputDirectory)/packages
          packTimezone: utc

          # SourceVersion is git hash, e.g. ba4edab919b22064ffd06911f5f3413b78889c9e.
          # SourceBranchName is modified/truncated to fit package name requirements.
          #
          # If you run the pipeline from the web gui of a PR, the branch name is like:
          #   refs/pull/15098313/merge
          # which here becomes just "merge", the last "path element".
          #
          # If you run the pipeline from the pipeline's web GUI:
          #   https://microsoft.visualstudio.com/OS/_build?definitionId=128656
          #
          # Then branch name like "dev/jaykrell/pip322-1"
          # becomes again the last path element: "pip322-1"
          #
          # To see the results, look at pipeline logs.
          #
          buildProperties: id=$(ob_createvpack_packagename);version=$(Parameters.vPack.majorVer).$(Parameters.vPack.minorVer)-$(Build.SourceBranchName).$(Build.SourceVersion)

      - script: |
          $(script_start)
          git config --global --unset http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_basecore.extraheader
          git config --global --unset http.https://dev.azure.com/windowspartners/MSCoreUEFI/_git/Core_UEFI_Internal.extraheader
          git config --global --unset http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_tiano_plus.extraheader
        displayName: Unset access token
