parameters:
- name: pipeline
  type: string
  values:
  - Official
  - PR
  default: false
- name: publishNuget
  type: boolean
  default: false
###############################################################################
# constants
- name: Nugets
  type: object
  default: [
    {definition: llvm.tools,    version: $(LlvmVersion), feed: $(LlvmFeed), downloadPath: $(PkgLlvm_Tools)},
    {definition: clang.headers, version: $(LlvmVersion), feed: $(LlvmFeed), downloadPath: $(PkgClang_Headers)}]
- name: Builds
  type: object
  # gcc is not to ship, because no Codeview and 64K aligned files (64K is easily fixed by using mingw tools).
  # gcc could be Windows-hosted if backward slashes are fixed.
  # Clang/amd64 is not yet to ship, stubs out assembly.
  default: [
    # TODO: What order for the columns?
    # TODO: What redundancy vs. derivation?
    {ob_nugetPublishing_enabled: true, Pool: Windows, Windows: true, Arch:     X64, Target:   DEBUG, ToolChainTag: VS2022, Extra: 'BLD_*_LEGACY_DEBUGGER=1'},
    {ob_nugetPublishing_enabled: true, Pool: Windows, Windows: true, Arch:     X64, Target: RELEASE, ToolChainTag: VS2022},
    {ob_nugetPublishing_enabled: true, Pool: Windows, Windows: true, Arch: AARCH64, Target:   DEBUG, ToolChainTag: VS2022},
    {ob_nugetPublishing_enabled: true, Pool: Windows, Windows: true, Arch: AARCH64, Target: RELEASE, ToolChainTag: VS2022},

    #
    # Salt (adds to flavor):
    #
    # Not perfectly systematic.
    # CV implies W.
    # CW implies W.
    #
    # Arch (not needed)   Target (not needed)    Tool            BuildHostOS (Pool)
    # A arm64             D debug                G  gcc          L Linux
    # X X64               R release              CV ClangVS      W Windows
    #                                            CW ClangWindows
    #                                            CL ClangLinux
    #                                            V  VS? M MSVC?
    #                                            M  Mingw?
    #                                            CP CLANGPDB?
    #                                            CD CLANGDWARF?
    #                                            CE CLANGELF?
    #                                            CP CLANGPE?
    #                                            GE GCCELF?
    #                                            GP GCCPE?
    #
    # Probably this should be the order for these columns.
    #
    # CLANG_BIN: Trailing slash is required. Setting this unconditionally (in vars.xml) breaks Linux build.
    {Pool: Windows, Windows: true, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}, Extra: 'BLD_*_LEGACY_DEBUGGER=1'},
    {Pool: Windows, Windows: true, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},
    {Pool: Windows, Windows: true, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: ADCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},
    {Pool: Windows, Windows: true, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: ARCV, Env: {CLANG_BIN: $(CLANGVS)/bin/}},

    {Pool: Windows, Windows: true, ClangWindows: true, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}, Extra: 'BLD_*_LEGACY_DEBUGGER=1'},
    {Pool: Windows, Windows: true, ClangWindows: true, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},
    {Pool: Windows, Windows: true, ClangWindows: true, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: ADCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},
    {Pool: Windows, Windows: true, ClangWindows: true, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: ARCW, Env: {CLANG_BIN: $(CLANGWIN_BIN)/}},

    {Pool: Linux, Linux: true, Arch:     X64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: XDCL, Extra: 'BLD_*_LEGACY_DEBUGGER=1'},
    {Pool: Linux, Linux: true, Arch:     X64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: XRCL},
    {Pool: Linux, Linux: true, Arch: AARCH64, Target:   DEBUG, ToolChainTag: CLANGPDB, Salt: ADCL},
    {Pool: Linux, Linux: true, Arch: AARCH64, Target: RELEASE, ToolChainTag: CLANGPDB, Salt: ARCL},

    {Pool: Linux, Linux: true, Arch:     X64, Target:   DEBUG, ToolChainTag:      GCC, Salt: XDG, Extra: 'BLD_*_LEGACY_DEBUGGER=1'},
    {Pool: Linux, Linux: true, Arch:     X64, Target: RELEASE, ToolChainTag:      GCC, Salt: XRG},
    {Pool: Linux, Linux: true, Arch: AARCH64, Target:   DEBUG, ToolChainTag:      GCC, Salt: ADG},
    {Pool: Linux, Linux: true, Arch: AARCH64, Target: RELEASE, ToolChainTag:      GCC, Salt: ARG}
    ]
###############################################################################
jobs:
  - ${{ each Build in parameters.Builds }}:
    # Keep historical job names for VS2022 and append _Salt for GCC/CLANGPDB.
    - job: ${{Build.Target}}_${{Build.Arch}}_${{Build.ToolChainTag}}${{iif(ne(Build.Salt, ''), format('_{0}', Build.Salt), '')}}
      pool:
        type: ${{ Build.Pool }}
      variables:
        ${{each pair in Build.Env}}:
          ${{pair.Key}}: ${{pair.Value}}
        Build.Arch: ${{Build.Arch}}
        Build.Extra: ${{Build.Extra}}
        Build.Target: ${{Build.Target}}
        Build.ToolChainTag: ${{Build.ToolChainTag}}
        Flavor:             $(Build.Target)_$(Build.Arch)
        Salt:               $(Build.Salt)
        DotSalt: ${{Build.DotSalt}}

        # Hypothetical Python version to install, not used.
        Env.PythonVersion: "3.10"

        # GCC prefix for Linux-hosted builds.
        GCC_AARCH64_PREFIX: '/usr/bin/aarch64-linux-gnu-'
        GCC_X64_PREFIX: '/usr/bin/x86_64-linux-gnu-'

        GIT_TERMINAL_PROMPT: "0"

        # Docker images to host pipeline on.
        # https://eng.ms/docs/products/onebranch/infrastructureandimages/containerimages/containerimages
        # TODO: Switch to AzureLinux
        LinuxContainerImage:   'onebranch.azurecr.io/linux/ubuntu-2404:latest'

        BuildDir:           Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)
        ob_outputDirectory: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        ob_nugetPublishing_enabled: ${{and(parameters.publishNuget, Build.ob_nugetPublishing_enabled)}}
        # Job name is included in artifact path and non-matrix job names must be unique.
        # Otherwise we would have "UnderSalt" like "DotSalt".
        # ob_artifactSuffix: '_$(Build.Arch)_$(Build.Target)'
        ${{ if and(eq(parameters.pipeline, 'Official'), Build.ob_nugetPublishing_enabled) }}:
          ob_createvpack_vpackdirectory: '$(ob_outputDirectory)/Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/Bin'
        PlatformPkg: "MsvmPkg"
        ToolChainTag: ${{Build.ToolChainTag}}
        WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # https://aka.ms/obpipelines/containers
      steps:
      - task: NuGetAuthenticate@1
        inputs:
          nuGetServiceConnections: WindowsPartners_NugetFeedConnection

      - task: PipAuthenticate@1
        displayName: 'Pip authenticate'
        inputs:
          artifactFeeds: '$(System.TeamProject)/$(System.TeamProject)_PublicPackages'

      - task: AzurePowerShell@5
        displayName: 'Set the access token'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
          azureSubscription: 'hyperv.uefi OneBranch Service Connection'
          ScriptType: 'InlineScript'
          azurePowerShellVersion: LatestVersion
          pwsh: true
          Inline: |
            git config --global http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_basecore.extraheader "AUTHORIZATION: Bearer $(System.AccessToken)"
            git config --global http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_tiano_plus.extraheader "AUTHORIZATION: Bearer $(System.AccessToken)"

      - script: python --version
        displayName: python_version

      # Python install fails on Linux and is not needed in any case.
      #- task: UsePythonVersion@0
      #  displayName: 'Install Python $(Env.PythonVersion)'
      #  inputs:
      #    versionSpec: '$(Env.PythonVersion)'
      #    architecture: 'x64'

      - ${{if Build.Linux}}:
        - script: sudo apt-get update -y
          displayName: apt up

        # gcc-* fails because of multiple version numbers.
        # TODO: Specialize on $ToolChainTag = GCC.
        - script: |
            cat $0
            sudo apt-get install -y gcc binutils \
              binutils-aarch64-linux-gnu binutils-x86-64-linux-gnu \
              gcc-aarch64-linux-gnu gcc-x86-64-linux-gnu \
              clang lld llvm

          displayName: apt inst

      # The nugets are downloaded into a strict read only cachable form, one Nuget per directory, like CoreXT.
      # Then copied to how clang wants them.
      - ${{if Build.ClangWindows}}:
        - ${{each Nuget in parameters.Nugets}}:
          - task: DownloadPackage@1
            displayName: get ${{Nuget.definition}}
            inputs: ${{Nuget}}
        # Always clean install.
        - script: |
            @echo on
            @type %0
            :: quotes to accomodate forward slashes
            rmdir /q/s                          "$(CLANGWIN)"
            xcopy /fivery "$(PkgLlvm_Tools)"    "$(CLANGWIN_BIN)" || goto :eof
            xcopy /fivery "$(PkgClang_Headers)" "$(CLANGWIN_INC)" || goto :eof
          displayName: install Windows clang

      - script: python -m pip install --upgrade -r pip_requirement_stable.txt --force-reinstall --no-cache-dir
        displayName: 'Add mu_build pip'

      - script: python $(PlatformPkg)/PlatformBuild.py --setup
        displayName: 'Platform build Setup'

      - script: python $(PlatformPkg)/PlatformBuild.py --update
        displayName: 'Platform build Update'

      - script: python $(PlatformPkg)/PlatformBuild.py $(Build.Extra) tool_chain_tag=$(Build.ToolChainTag) BUILDREPORTING=TRUE BUILDREPORT_TYPES="PCD DEPEX FLASH BUILD_FLAGS LIBRARY" TARGET=$(Build.Target) BUILD_ARCH=$(Build.Arch) LaunchLogOnSuccess=FALSE LaunchLogOnError=FALSE
        displayName: 'Run Build '

      - ${{if Build.Linux}}:
        - script: |
            ls   Build
            cat  Build/B*.txt
          condition: succeededOrFailed()
          continueOnError: true
          displayName: "logs"
      - ${{else}}:
        - script: |
            dir  Build
            type Build\B*.txt
          condition: succeededOrFailed()
          continueOnError: true
          displayName: "logs"

      - task: CopyFiles@2
        displayName: "Copy build logs"
        inputs:
          targetFolder: "$(Build.ArtifactStagingDirectory)"
          SourceFolder: "Build"
          contents: |
            BuildLog.txt
            BUILDLOG_*.txt
            BUILDLOG_*.md
            **/BUILD_REPORT.txt
            CI_*.txt
            CI_*.md
            CISETUP.txt
            SETUPLOG.txt
            UPDATE_LOG.txt
            PREVALLOG.txt
            TestSuites.xml
            **/BUILD_TOOLS_REPORT.html
            **/OVERRIDELOG.TXT
            BASETOOLS_BUILD*.*
            **/FD_REPORT.HTML
          flattenFolders: true
        condition: succeededOrFailed()

      - task: CopyFiles@2
        condition: failed()
        continueOnError: true
        displayName: Copy all, for debugging
        inputs:
          SourceFolder: Build
          Contents: '**'
          TargetFolder: $(ob_outputDirectory)/all for debugging

      - task: CopyFiles@2
        continueOnError: true
        displayName: "Copy Files for 'Publish build logs' publish task"
        inputs:
          SourceFolder: "$(Build.ArtifactStagingDirectory)"
          # Nugets are downloaded here so * instead of **.
          Contents: '*'
          TargetFolder: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/Build Logs $(System.JobName)
        condition: succeededOrFailed()

      - task: CopyFiles@2
        displayName: "Copy FV/MSVM.fd for 'Publish Artifact: Firmware Bin File $(Build.Target)_$(Build.Arch)' publish task"
        inputs:
          Contents: 'Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/FV/MSVM.fd'
          TargetFolder: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/Firmware Binary File $(Build.Target)_$(Build.Arch)

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: CopyFiles@2
          displayName: "Copy PDB/ for 'Publish Artifact: Firmware Bin File $(Build.Target)_$(Build.Arch)' publish task"
          inputs:
            SourceFolder: 'Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/PDB/'
            Contents: '**'
            TargetFolder: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/Firmware PDB Files $(Build.Target)_$(Build.Arch)

      - task: CopyFiles@2
        displayName: "Copy MAP/ for 'Publish Artifact: Firmware Map Files $(Build.Target)_$(Build.Arch)' publish task"
        inputs:
          SourceFolder: 'Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/MAP/'
          Contents: '**'
          TargetFolder: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/Firmware Map Files $(Build.Target)_$(Build.Arch)

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: PublishSymbols@2
          displayName: 'Publish symbols to the symbol server'
          inputs:
            SearchPattern: 'Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/PDB/*.pdb'
            IndexSources: true
            SymbolServerType: 'TeamServices'
            SymbolsProduct: 'Hyper-V UEFI'
            enablesymbolspublishing: true
          continueOnError: true

      - task: Powershell@2
        displayName: 'Compute Hash and copy firmware to vpack folder'
        inputs:
          targetType: 'inline'
          script: |
            $LocalCommit = & 'git' rev-parse "@"
            Write-Host "##vso[task.setvariable variable=Build.CommitHash]$LocalCommit"
            $folder = "$(ob_outputDirectory)/Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/Bin"
            New-Item $folder -Type Directory
            copy-item "Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/FV/MSVM.fd" $folder
            copy-item "Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/$(Build.Arch)/MsvmPkg/AcpiTables/AcpiTables/OUTPUT/Dsdt.aml" $folder
            copy-item "MsvmPkg/Include/BiosInterface.h" $folder

      - ${{ if ne(Build.ToolChainTag, 'GCC')}}:
        - task: Powershell@2
          displayName: 'Copy PDBs to vpack folder'
          inputs:
            targetType: 'inline'
            script: |
              $folder = "$(ob_outputDirectory)/Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/Bin"
              copy-item "Build/Msvm$(Build.Arch)/$(Build.Target)_$(Build.ToolChainTag)/PDB" $folder -Recurse

      - ${{ if eq(parameters.publishNuget, true) }}:
        - task: NuGetCommand@2
          displayName: 'Pack the NuGet package'
          inputs:
            command: 'pack'
            packagesToPack: '$(PlatformPkg)/HyperVUefi.NuSpec'
            packDestination: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT/packages'
            packTimezone: 'utc'
            buildProperties: 'id=$(Build.Repository.Name).mscoreuefi.$(Build.Arch).$(Build.Target)$(DotSalt);version=$(Parameters.vPack.majorVer).$(Parameters.vPack.minorVer)-$(Build.SourceBranchName).$(Build.SourceVersion)'

      - script: |
          git config --global --unset http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_basecore.extraheader
          git config --global --unset http.https://dev.azure.com/windowspartners/MSCoreUEFI/_git/Core_UEFI_Internal.extraheader
          git config --global --unset http.https://dev.azure.com/microsoft/OS/_git/hyperv.uefi.mu_tiano_plus.extraheader
        displayName: 'Unset access token'
